export const Title = [
  { appellation: '稱謂' },
  { mr: '先生' },
  { ms: '女士' },
  { mx: '不明' },
  { name: '姓名' },
  { tel: '電話' },
  { email: 'email' },
  { cities: '縣市' },
  { address: '地址' },
  { expressWay: '運送方式' },
  { period: '約 3~7 個工作天' },
  { express: 'DHL 貨運' },
  { expressTime: '48 小時內送達' },
  { payInfo: '付款資訊' },
  { creditName: '持卡人姓名' },
  { creditNumber: '卡號' },
  { expiration: '有效期限' },
  { cvc: 'CVC / CCV' },

]