export const Titles = 
   {
    expressAddress: '運送地址',
    appellation: '稱謂',
    mr: '先生',
    ms: '女士',
    mx: '不明',
    name: '姓名',
    namePlace: '請輸入姓名',
    tel: '電話',
    telPlace: '請輸入行動電話',
    email: 'email',
    emailPlace: '請輸入電子郵件',
    cities: '縣市',
    cityPlace: '請選擇縣市',
    address: '地址',
    addressPlace: '請輸入地址',
    expressWay: '運送方式', 
    normalExpress: '標準運送',
    period: '約 3~7 個工作天',
    express: 'DHL 貨運',
    free: '免費',
    unfree: '$500',
    expressTime: '48 小時內送達',
    creditTitle: '付款資訊',
    creditName: '持卡人姓名',
    creditPlace: 'John Doe', 
    cardNumber: '卡號',
    creditNumber: '1111 2222 3333 4444',
    expiration: '有效期限',
    creditDate: 'MM/YY',
    cvc: 'CVC / CCV',
    cvcContent: '123'
  }

